name: Build, Test & Generate Docs

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restoring dependencies...
      run: dotnet restore Ucu.Andis.ArchitectureMetrics.sln

    - name: Building...
      run: dotnet build Ucu.Andis.ArchitectureMetrics.sln --configuration Release --no-restore

    - name: Running tests...
      run: dotnet test Ucu.Andis.ArchitectureMetrics.sln --configuration Release --no-build --verbosity normal
